version: '3'

services:
  web:
    build: .
    command: python app.py
    volumes:
      - .:/app
    ports:
      - '5000:5000'
    depends_on:
      - dynamodb-local
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    ports:
      - "8000:8000"